version: "3"
networks:
  color-tracking-net:
    driver: bridge
services:
  db:
    image: postgres:9.6-alpine
    container_name: db
    networks:
      - "color-tracking-net"
    restart: always
    environment:
      POSTGRES_USER: juan
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    networks:
      - "color-tracking-net"
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka: # TODO: use custom Container -> https://github.com/karafka/karafka/wiki/Deployment#docker
    image: wurstmeister/kafka:latest
    container_name: kafka
    networks:
      - "color-tracking-net"
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
  api:
    # use `image` for starting api without the need of refreshing for changes
    # image: juanroldan1989/color-tracking-api

    # use `build` for starting api and refreshing it when making changes
    build: .
    container_name: api
    networks:
      - "color-tracking-net"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - kafka
      - zookeeper
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: 4aa41ef3d067551bed489ff4e4f3357886923e27ab83a37dd1ab26014b050d5f8e3fe6bdf26906ac04903d6466d7e452e6443d7c70a83537de254bbc4fa9a188
volumes:
  postgres:
