version: "3"

volumes:
  postgres:

networks:
  color-tracking-net:
    driver: bridge

services:
  db:
    image: postgres:9.6-alpine
    container_name: db
    networks:
      - "color-tracking-net"
    restart: always
    environment:
      POSTGRES_USER: juan
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: redis
    networks:
      - "color-tracking-net"
    ports:
      - "6379:6379"
    command: redis-server
    depends_on:
      - api
      - karafka-consumer

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - "color-tracking-net"
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - "color-tracking-net"
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "hover_on_colors:1:1,click_on_colors:1:1"
    depends_on:
      - db
      - zookeeper

  api:
    image: juanroldan1989/color-tracking-api
    # build: .
    container_name: api
    networks:
      - "color-tracking-net"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - kafka
      - zookeeper
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      REDIS_AS_DB: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CACHE_URL: redis://127.0.0.1:6379
      SECRET_KEY_BASE: "secret_key_base"

  karafka-consumer:
    image: juanroldan1989/color-tracking-api
    # build: .
    container_name: karafka-consumer
    networks:
      - "color-tracking-net"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
      - kafka
      - zookeeper
      - api
    command: bundle exec karafka server
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      REDIS_AS_DB: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CACHE_URL: redis://127.0.0.1:6379
      RUN_MIGRATIONS: "false"
      SECRET_KEY_BASE: "secret_key_base"
