# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.0.0"

gem "karafka",   ">= 2.0.0.alpha2"
gem "pg",        "~> 1.4.2"
gem "puma",      "~> 5.6.4"
gem "rack-cors", "~> 1.1.1"
gem "rails",     "~> 7.0"

group :development, :test do
  gem "karafka-testing", ">= 2.0.0.alpha3"
  gem "rspec",           "~> 3.11.0"
  # gem "rubocop"
end
