# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.0.0"

gem "karafka", ">= 2.0.0.alpha2"
gem "puma",    "~> 5.6.4"
gem "rails",   "~> 7.0"
gem "sqlite3", "~> 1.4"

group :development, :test do
  gem "karafka-testing", ">= 2.0.0.alpha3"
  gem "rspec",           "~> 3.11.0"
end
